# Generated by Django 4.2 on 2025-12-22 15:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago Recibido (Desembolso)', 'verbose_name_plural': 'Pagos Recibidos (Desembolsos)'},
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(verbose_name='Fecha del Desembolso'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto del Desembolso'),
        ),
        migrations.CreateModel(
            name='OrdenCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código OC')),
                ('descripcion', models.TextField(verbose_name='Descripción del Cambio')),
                ('monto_adicional', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Adicional')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de Solicitud')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente Aprobación'), ('aprobada', 'Aprobada'), ('en_ejecucion', 'En Ejecución'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('solicitado_por', models.CharField(help_text='Cliente o responsable', max_length=200, verbose_name='Solicitado Por')),
                ('justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_cambio', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Orden de Cambio',
                'verbose_name_plural': 'Órdenes de Cambio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
