# Generated by Django 4.2 on 2025-12-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_pago_options_alter_pago_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='concepto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Concepto del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('deposito', 'Depósito')], max_length=20),
        ),
    ]
