# Generated by Django 4.2 on 2025-12-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_pago_concepto_alter_pago_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencambio',
            name='solicitado_por',
            field=models.CharField(blank=True, help_text='Cliente o responsable', max_length=200, null=True, verbose_name='Solicitado Por'),
        ),
    ]
