# Generated by Django 4.2 on 2025-12-22 19:08

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_ordencambio_solicitado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Deducción')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('porcentaje_sugerido', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje sugerido si aplica (ej: IHSS 7%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='% Sugerido')),
                ('requiere_referencia', models.BooleanField(default=False, help_text='Indica si requiere número de referencia (ej: número de préstamo)', verbose_name='Requiere Referencia')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Deducción',
                'verbose_name_plural': 'Tipos de Deducciones',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prestamo', models.CharField(max_length=20, unique=True, verbose_name='Número de Préstamo')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total del Préstamo')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto por Cuota')),
                ('numero_cuotas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Cuotas')),
                ('cuotas_pagadas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cuotas Pagadas')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Pendiente')),
                ('fecha_otorgamiento', models.DateField(verbose_name='Fecha de Otorgamiento')),
                ('fecha_primer_descuento', models.DateField(verbose_name='Fecha Primer Descuento')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo del Préstamo')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='proyectos.empleado')),
            ],
            options={
                'verbose_name': 'Préstamo a Empleado',
                'verbose_name_plural': 'Préstamos a Empleados',
                'ordering': ['-fecha_otorgamiento'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_anterior', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Salario Anterior')),
                ('salario_nuevo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Salario Nuevo')),
                ('tipo_cambio', models.CharField(choices=[('aumento', 'Aumento'), ('disminucion', 'Disminución'), ('ajuste', 'Ajuste')], max_length=20)),
                ('porcentaje_cambio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% de Cambio')),
                ('fecha_cambio', models.DateField(verbose_name='Fecha del Cambio')),
                ('fecha_efectiva', models.DateField(help_text='Fecha desde la cual aplica el nuevo salario', verbose_name='Fecha Efectiva')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo del Cambio')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autorizado Por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_salarios', to='proyectos.empleado')),
            ],
            options={
                'verbose_name': 'Historial de Salario',
                'verbose_name_plural': 'Historial de Salarios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='DeduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Deducido')),
                ('porcentaje_aplicado', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje si fue calculado sobre el salario', max_digits=5, null=True, verbose_name='% Aplicado')),
                ('numero_referencia', models.CharField(blank=True, help_text='Ej: número de préstamo, número de anticipo, etc.', max_length=50, null=True, verbose_name='Número de Referencia')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Adicional')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('detalle_planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducciones_detalle', to='proyectos.detalleplanilla')),
                ('tipo_deduccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.tipodeduccion', verbose_name='Tipo de Deducción')),
            ],
            options={
                'verbose_name': 'Detalle de Deducción',
                'verbose_name_plural': 'Detalles de Deducciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='AnticipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_anticipo', models.CharField(max_length=20, unique=True, verbose_name='Número de Anticipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto del Anticipo')),
                ('fecha_anticipo', models.DateField(verbose_name='Fecha del Anticipo')),
                ('fecha_descuento', models.DateField(blank=True, null=True, verbose_name='Fecha de Descuento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Descuento'), ('descontado', 'Descontado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo del Anticipo')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipos', to='proyectos.empleado')),
                ('planilla_descuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticipos_descontados', to='proyectos.planilla', verbose_name='Planilla donde se Descontó')),
            ],
            options={
                'verbose_name': 'Anticipo de Salario',
                'verbose_name_plural': 'Anticipos de Salario',
                'ordering': ['-fecha_anticipo'],
            },
        ),
    ]
