# Generated by Django 4.2 on 2025-12-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_tipodeduccion_prestamoempleado_historialsalario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaGasto',
        ),
    ]
