# Generated by Django 4.2 on 2025-12-23 13:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_remove_gasto_categoria_delete_categoriagasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: IHSS, ISR, Préstamo, Anticipo, etc.', max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto a Deducir')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducciones', to='proyectos.empleado', verbose_name='Empleado')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducciones', to='proyectos.planilla', verbose_name='Planilla')),
            ],
            options={
                'verbose_name': 'Deducción',
                'verbose_name_plural': 'Deducciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.RemoveField(
            model_name='deducciondetalle',
            name='detalle_planilla',
        ),
        migrations.RemoveField(
            model_name='deducciondetalle',
            name='tipo_deduccion',
        ),
        migrations.RemoveField(
            model_name='historialsalario',
            name='autorizado_por',
        ),
        migrations.RemoveField(
            model_name='historialsalario',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='prestamoempleado',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='AnticipoEmpleado',
        ),
        migrations.DeleteModel(
            name='DeduccionDetalle',
        ),
        migrations.DeleteModel(
            name='HistorialSalario',
        ),
        migrations.DeleteModel(
            name='PrestamoEmpleado',
        ),
        migrations.DeleteModel(
            name='TipoDeduccion',
        ),
    ]
