# Generated by Django 4.2 on 2025-12-23 17:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_deduccion_remove_deducciondetalle_detalle_planilla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Horas extra nocturnas, Horas extra domingo, etc.', max_length=200, verbose_name='Descripción')),
                ('cantidad_horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad de Horas')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto a Pagar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extra', to='proyectos.empleado', verbose_name='Empleado')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extra', to='proyectos.planilla', verbose_name='Planilla')),
            ],
            options={
                'verbose_name': 'Hora Extra',
                'verbose_name_plural': 'Horas Extra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Bonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Bono por rendimiento, Incentivo, etc.', max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto de Bonificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones', to='proyectos.empleado', verbose_name='Empleado')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones', to='proyectos.planilla', verbose_name='Planilla')),
            ],
            options={
                'verbose_name': 'Bonificación',
                'verbose_name_plural': 'Bonificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
