# Generated by Django 4.2 on 2025-12-23 18:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_horaextra_bonificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salario Anterior')),
                ('salario_nuevo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Salario Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('motivo', models.CharField(blank=True, help_text='Ej: Aumento anual, Promoción, Ajuste por inflación, etc.', max_length=200, verbose_name='Motivo del Cambio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_salarios', to='proyectos.empleado', verbose_name='Empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_salario_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realizó el Cambio')),
            ],
            options={
                'verbose_name': 'Historial de Salario',
                'verbose_name_plural': 'Historial de Salarios',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
