# Generated by Django 4.2 on 2025-12-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_historialsalario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplanilla',
            name='bonificaciones',
        ),
        migrations.RemoveField(
            model_name='detalleplanilla',
            name='deducciones',
        ),
        migrations.RemoveField(
            model_name='detalleplanilla',
            name='horas_extra',
        ),
    ]
