# Generated by Django 4.2 on 2025-12-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_remove_detalleplanilla_bonificaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplanilla',
            name='dias_trabajados',
        ),
        migrations.AlterField(
            model_name='detalleplanilla',
            name='salario_devengado',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Salario Devengado'),
        ),
    ]
