# Generated by Django 4.2 on 2025-12-25 17:49

from django.db import migrations, models


def migrar_roles_antiguos(apps, schema_editor):
    """
    Migra los roles antiguos a los nuevos:
    - administrador -> gerente
    - gerente_proyecto -> supervisor
    - supervisor_obra -> auxiliar
    - consultor -> usuario
    - contador -> contador (sin cambios)
    """
    Usuario = apps.get_model('proyectos', 'Usuario')

    mapeo_roles = {
        'administrador': 'gerente',
        'gerente_proyecto': 'supervisor',
        'supervisor_obra': 'auxiliar',
        'consultor': 'usuario',
        'contador': 'contador',
    }

    for usuario in Usuario.objects.all():
        if usuario.rol in mapeo_roles:
            usuario.rol = mapeo_roles[usuario.rol]
            usuario.save()


def revertir_roles(apps, schema_editor):
    """Revierte los roles a los antiguos en caso de rollback"""
    Usuario = apps.get_model('proyectos', 'Usuario')

    mapeo_roles_reverso = {
        'gerente': 'administrador',
        'supervisor': 'gerente_proyecto',
        'auxiliar': 'supervisor_obra',
        'usuario': 'consultor',
        'contador': 'contador',
    }

    for usuario in Usuario.objects.all():
        if usuario.rol in mapeo_roles_reverso:
            usuario.rol = mapeo_roles_reverso[usuario.rol]
            usuario.save()


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_remove_detalleplanilla_dias_trabajados_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_roles_antiguos, revertir_roles),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('contador', 'Contador'), ('auxiliar', 'Auxiliar'), ('usuario', 'Usuario')], default='usuario', max_length=20, verbose_name='Rol'),
        ),
    ]
