# Generated by Django 4.2 on 2025-12-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único para identificar la empresa en URLs', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('rtn', models.CharField(max_length=14, unique=True, verbose_name='RTN')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo')),
                ('activa', models.BooleanField(default=True, verbose_name='Empresa Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rtn',
            field=models.CharField(max_length=14, verbose_name='RTN'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=20, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rtn',
            field=models.CharField(max_length=14, verbose_name='RTN'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='proyectos.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='proyectos.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='proyectos.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el usuario. Superusuarios pueden no tener empresa asignada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='proyectos.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('empresa', 'codigo'), ('empresa', 'rtn')},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('empresa', 'codigo'), ('empresa', 'dni')},
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('empresa', 'codigo'), ('empresa', 'rtn')},
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together={('empresa', 'codigo')},
        ),
    ]
