# Generated by Django 4.2 on 2025-12-25 18:44

from django.db import migrations


def crear_empresa_default_y_asignar(apps, schema_editor):
    """
    Crea una empresa por defecto y asigna todos los registros existentes a ella.
    """
    Empresa = apps.get_model('proyectos', 'Empresa')
    Cliente = apps.get_model('proyectos', 'Cliente')
    Proveedor = apps.get_model('proyectos', 'Proveedor')
    Empleado = apps.get_model('proyectos', 'Empleado')
    Proyecto = apps.get_model('proyectos', 'Proyecto')
    Usuario = apps.get_model('proyectos', 'Usuario')

    # Crear empresa por defecto solo si no existe
    empresa_default, created = Empresa.objects.get_or_create(
        codigo='DEFAULT',
        defaults={
            'nombre': 'Constructora Principal',
            'razon_social': 'Constructora Principal S.A.',
            'rtn': '0000000000000',
            'activa': True,
        }
    )

    # Asignar todos los clientes a la empresa default
    Cliente.objects.filter(empresa__isnull=True).update(empresa=empresa_default)

    # Asignar todos los proveedores a la empresa default
    Proveedor.objects.filter(empresa__isnull=True).update(empresa=empresa_default)

    # Asignar todos los empleados a la empresa default
    Empleado.objects.filter(empresa__isnull=True).update(empresa=empresa_default)

    # Asignar todos los proyectos a la empresa default
    Proyecto.objects.filter(empresa__isnull=True).update(empresa=empresa_default)

    # Asignar todos los usuarios no-superusuarios a la empresa default
    Usuario.objects.filter(empresa__isnull=True, is_superuser=False).update(empresa=empresa_default)


def revertir_asignacion(apps, schema_editor):
    """Revierte la asignación de empresa (pone todos en NULL)"""
    Cliente = apps.get_model('proyectos', 'Cliente')
    Proveedor = apps.get_model('proyectos', 'Proveedor')
    Empleado = apps.get_model('proyectos', 'Empleado')
    Proyecto = apps.get_model('proyectos', 'Proyecto')
    Usuario = apps.get_model('proyectos', 'Usuario')

    Cliente.objects.all().update(empresa=None)
    Proveedor.objects.all().update(empresa=None)
    Empleado.objects.all().update(empresa=None)
    Proyecto.objects.all().update(empresa=None)
    Usuario.objects.filter(is_superuser=False).update(empresa=None)


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_empresa_alter_cliente_codigo_alter_cliente_rtn_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_empresa_default_y_asignar, revertir_asignacion),
    ]
