# Generated by Django 4.2 on 2025-12-28 04:24

import django.core.validators
from django.db import migrations, models
import proyectos.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_asignar_empresa_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Adjuntar factura, recibo o documento relacionado (PDF, Imagen, Excel). Máximo 10MB.', null=True, upload_to=proyectos.models.gasto_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'xlsx', 'xls', 'doc', 'docx'], message='Solo se permiten archivos PDF, imágenes (JPG, PNG), Excel o Word.')], verbose_name='Factura/Documento Adjunto'),
        ),
    ]
