# Generated by Django 4.2 on 2025-12-30 06:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import proyectos.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_gasto_archivo_adjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre/Descripción')),
                ('tipo', models.CharField(choices=[('retroexcavadora', 'Retroexcavadora'), ('excavadora', 'Excavadora'), ('bulldozer', 'Bulldozer'), ('camion', 'Camión'), ('grua', 'Grúa'), ('compactadora', 'Compactadora'), ('motoniveladora', 'Motoniveladora'), ('cargador', 'Cargador Frontal'), ('vibrador', 'Vibrador'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de Maquinaria')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('placa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa/Matrícula')),
                ('horometro_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Horas acumuladas de uso de la maquinaria', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Horómetro Actual (horas)')),
                ('tarifa_hora', models.DecimalField(decimal_places=2, help_text='Costo por hora de uso', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa por Hora')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20, verbose_name='Estado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinarias', to='proyectos.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.AlterField(
            model_name='gasto',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Adjuntar factura, recibo o documento relacionado (PDF, Imagen, Excel). Máximo 10MB.', null=True, upload_to=proyectos.models.gasto_upload_path, validators=[proyectos.models.validar_tamanio_archivo, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'xlsx', 'xls', 'doc', 'docx'], message='Solo se permiten archivos PDF, imágenes (JPG, PNG), Excel o Word.')], verbose_name='Factura/Documento Adjunto'),
        ),
        migrations.CreateModel(
            name='UsoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('horometro_inicial', models.DecimalField(decimal_places=2, help_text='Lectura del horómetro al iniciar', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Horómetro Inicial')),
                ('horometro_final', models.DecimalField(blank=True, decimal_places=2, help_text='Lectura del horómetro al finalizar', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Horómetro Final')),
                ('tarifa_aplicada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa Aplicada (por hora)')),
                ('operador', models.CharField(blank=True, max_length=200, null=True, verbose_name='Operador')),
                ('descripcion_trabajo', models.TextField(blank=True, null=True, verbose_name='Descripción del Trabajo Realizado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='proyectos.maquinaria', verbose_name='Maquinaria')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_maquinaria', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Uso de Maquinaria',
                'verbose_name_plural': 'Usos de Maquinaria',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
