# Generated by Django 4.2 on 2025-12-30 06:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_maquinaria_alter_gasto_archivo_adjunto_usomaquinaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usomaquinaria',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_maquinaria_operados', to='proyectos.empleado', verbose_name='Operador'),
        ),
        migrations.CreateModel(
            name='HistorialTarifaMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tarifa Anterior')),
                ('tarifa_nueva', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tarifa Nueva')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('motivo', models.CharField(blank=True, help_text='Ej: Ajuste por inflación, Cambio de mercado, etc.', max_length=200, verbose_name='Motivo del Cambio')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_tarifas', to='proyectos.maquinaria', verbose_name='Maquinaria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_tarifa_maquinaria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realizó el Cambio')),
            ],
            options={
                'verbose_name': 'Historial de Tarifa de Maquinaria',
                'verbose_name_plural': 'Historial de Tarifas de Maquinaria',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
