# Generated by Django 4.2 on 2025-12-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_alter_usomaquinaria_operador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('contador', 'Contador'), ('auxiliar', 'Auxiliar'), ('operador', 'Operador'), ('usuario', 'Usuario')], default='usuario', max_length=20, verbose_name='Rol'),
        ),
    ]
