# Generated by Django 4.2 on 2025-12-30 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0018_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema asociado a este empleado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema'),
        ),
    ]
