# Generated by Django 4.2 on 2025-12-30 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_empleado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='usomaquinaria',
            name='operador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'operador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_maquinaria_operados', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
    ]
