# Generated by Django 4.2 on 2025-12-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_alter_usomaquinaria_operador_to_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(editable=False, help_text='Código generado automáticamente del nombre (se usa en URLs)', max_length=200, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(help_text='Nombre único que identifica la empresa', max_length=200, unique=True, verbose_name='Nombre Comercial'),
        ),
    ]
