# Generated by Django 4.2 on 2025-12-31 02:10

from django.db import migrations
import re


def regenerate_codigos(apps, schema_editor):
    """
    Regenera los códigos de todas las empresas basándose en sus nombres.
    """
    Empresa = apps.get_model('proyectos', 'Empresa')

    for empresa in Empresa.objects.all():
        # Generar código desde nombre usando la misma lógica del modelo
        codigo = empresa.nombre.upper()
        codigo = re.sub(r'[^\w\s-]', '', codigo)  # Eliminar caracteres especiales
        codigo = re.sub(r'[-\s]+', '-', codigo)    # Reemplazar espacios con guiones
        empresa.codigo = codigo.strip('-')
        empresa.save()


def reverse_regenerate_codigos(apps, schema_editor):
    """
    No se puede revertir esta migración de datos de forma automática.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_auto_generate_empresa_codigo'),
    ]

    operations = [
        migrations.RunPython(regenerate_codigos, reverse_regenerate_codigos),
    ]
