# Generated by Django 4.2 on 2025-12-31 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_regenerate_empresa_codigos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('tipo', models.CharField(choices=[('setup', 'Cuota de Instalación (Una vez)'), ('mensual', 'Plan Mensual'), ('anual', 'Plan Anual')], max_length=20, verbose_name='Tipo de Plan')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (L.)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Plan Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['tipo', 'precio'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='cuota_instalacion_pagada',
            field=models.BooleanField(default=False, verbose_name='Cuota de Instalación Pagada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado_suscripcion',
            field=models.CharField(choices=[('trial', 'En Trial'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='trial', max_length=20, verbose_name='Estado de Suscripción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_expiracion_suscripcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_inicio_suscripcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio de Suscripción'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_suscripcion',
            field=models.CharField(choices=[('trial', 'Trial (15 días gratis)'), ('mensual', 'Plan Mensual'), ('anual', 'Plan Anual')], default='trial', max_length=20, verbose_name='Tipo de Suscripción'),
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado (L.)')),
                ('metodo_pago', models.CharField(choices=[('transferencia_bac', 'Transferencia BAC'), ('transferencia_occidente', 'Transferencia Banco de Occidente'), ('deposito_bac', 'Depósito en efectivo BAC'), ('deposito_occidente', 'Depósito en efectivo Occidente'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=30, verbose_name='Método de Pago')),
                ('numero_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Referencia/Comprobante')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='pagos/comprobantes/', verbose_name='Comprobante de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Verificación'), ('verificado', 'Verificado y Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado del Pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha del Pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='proyectos.empresa', verbose_name='Empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.plan', verbose_name='Plan Pagado')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
