# Generated by Django 4.2 on 2025-12-31 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0023_sistema_suscripciones_saas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ip_registro',
            field=models.GenericIPAddressField(blank=True, help_text='IP desde donde se registró la empresa', null=True, verbose_name='IP de Registro'),
        ),
        migrations.CreateModel(
            name='RegistroTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('email_empresa', models.EmailField(max_length=254, verbose_name='Email de Empresa')),
                ('email_usuario', models.EmailField(max_length=254, verbose_name='Email de Usuario')),
                ('rtn', models.CharField(max_length=14, verbose_name='RTN')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('motivo_bloqueo', models.TextField(blank=True, null=True, verbose_name='Motivo de Bloqueo')),
                ('empresa_creada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.empresa', verbose_name='Empresa Creada')),
            ],
            options={
                'verbose_name': 'Registro de Trial',
                'verbose_name_plural': 'Registros de Trials',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='registrotrial',
            index=models.Index(fields=['ip_address'], name='proyectos_r_ip_addr_e3eeae_idx'),
        ),
        migrations.AddIndex(
            model_name='registrotrial',
            index=models.Index(fields=['email_empresa'], name='proyectos_r_email_e_5b53f6_idx'),
        ),
        migrations.AddIndex(
            model_name='registrotrial',
            index=models.Index(fields=['fecha_registro'], name='proyectos_r_fecha_r_68760b_idx'),
        ),
    ]
