# Generated by Django 4.2 on 2025-12-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0024_empresa_ip_registro_registrotrial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plan_incluye_maquinaria',
            field=models.BooleanField(default=True, help_text='Plan Completo incluye gestión de maquinaria. Plan Básico no incluye este módulo.', verbose_name='Plan Incluye Módulo de Maquinaria'),
        ),
    ]
