# Generated by Django 4.2 on 2025-12-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0026_pagorecibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plan_elegido',
            field=models.CharField(blank=True, choices=[('mensual_nuevo_basico', 'Plan Mensual Básico'), ('anual_1_nuevo_basico', 'Plan Anual Básico (1 año)'), ('anual_2_nuevo_basico', 'Plan Bianual Básico (2 años)'), ('mensual_nuevo_completo', 'Plan Mensual Completo'), ('anual_1_nuevo_completo', 'Plan Anual Completo (1 año)'), ('anual_2_nuevo_completo', 'Plan Bianual Completo (2 años)')], help_text='Plan que el cliente seleccionó al momento del registro (se activa cuando paga)', max_length=30, verbose_name='Plan Elegido al Registrarse'),
        ),
    ]
